### ISSUE TITLE
Button integreation 

### ISSUE THREAD

**Issue by Aidam7** [scp-cs/Thorn#33]
Discord recently added buttons for bots to work with. They're basically a different way to embed links and stuff, we could use them to make the quick-link function cleaner because the long links are an eye sore. From the Discord documentation we can have up to 5 buttons in 4 colours (wow, so much colours...thank our Corporate Overlord), emojis are supported too so that's a plus I guess. I'm attatching a link to the documentation [here](https://discord.com/developers/docs/interactions/message-components). Now the great question, are they worth the trouble?

![image](https://user-images.githubusercontent.com/55688345/120216562-782ae900-c237-11eb-895f-391a6747f416.png)

**Comment by chamik** [comment]
Yes, I've seen this. The issue is that the folks maintaining Discord.Net take their time and haven't even properly implemented [Slash Commands yet](https://github.com/discord-net/Discord.Net/pull/1717), so this will probably be implemented even later. Though I'll make sure to have a look at it once it's relevant.

**Comment by chamik** [comment]
do we need this?

**Comment by Aidam7** [comment]
Would be nice but we kinda lost the need for them given the removal of wiki fetching and stuff like that
